### ISSUE TITLE
WebView can't run as administrator

### ISSUE THREAD

**Issue by PoulBak** [windows-toolkit/Microsoft.Toolkit.Win32#13]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one)

## Current behavior
If you try to your app as adminstrator (elevated), the app will not show, no errors or messages, it just doesn't show.

The reason this became an issue, was that I primarily develop websites, and to debug the local IIS, Visual Studio must run as admin, so I have changed the VS shortcut to require that. Unfornately this Means, that any app launched will also run as admin.

The proplem is that it's impossible to debug, when nothing is shown.

## Expected behavior

The app should run (Edge can run as admin). If that isn't possible, I suggest, you check at startup, whether it runs as admin and then _**throw an exception: "WebView can't run as administrator".**_

That will save hours of frustrating debugging for many people,

## Minimal reproduction of the problem with instructions
Run Visual Studio as admin, now launch an app with WebView.

## Environment
```
Nuget Package(s):  Microsoft Toolkit Windows Forms WebView

Package Version(s): 5.01

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x ] October 2018 Update (17763)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x ] October 2018 Update (17763)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x ] 2017 (version: 15.9.4)
- [ ] 2017 Preview (version: )

```

**Comment by keiserS** [comment]
This also happens when you use new version of Toolkit v.5.
Telling user he can't run as admin is not acceptable imho! It would be better to figure out what is the real cause of this and repair it, isn't it?

VS running in normal mode, starts debugging of the app without the problem, VS running in elevated mode ("Run as Administrator") give that error, and unfortunately I need elevated mode since have self hosted WebApi app (which will not run in normal mode) and win forms App using WebView (not working in normal mode?!?!).

So is there any news about this and how to overcome and resolve this? and what is the real cause of exception when VS/app is being run in elevated mode?

Exception being raised in InitializeComponent method is:
`**The remote procedure call failed. (Exception from HRESULT: 0x800706BE)**`

Can someone get insight how to overcome this? and what is the real reason.. here is stack trace:
```
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.WinRT.WebViewControlProcess.<CreateWebViewControlHostAsync>d__16.MoveNext() in D:\a\1\s\WebView.Shared\Interop\WinRT\WebViewControlProcess.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Toolkit.Forms.UI.Controls.WebViewControlProcessExtensions.CreateWebViewControlHost(WebViewControlProcess process, IntPtr hostWindowHandle, Rectangle bounds) in D:\a\1\s\Microsoft.Toolkit.Forms.UI.Controls.WebView\WebViewControlProcessExtensions.cs:line 178
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.Initialize() in D:\a\1\s\Microsoft.Toolkit.Forms.UI.Controls.WebView\WebView.Init.cs:line 129
   at Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit() in D:\a\1\s\Microsoft.Toolkit.Forms.UI.Controls.WebView\WebView.Init.cs:line 67

```

**Comment by michael-hawker** [comment]
@joshholmes any info you can provide on this?

**Comment by NikasZalias** [comment]
Is there any new info about this?

**Comment by NikasZalias** [comment]
Is there any new info about this?

**Comment by NikasZalias** [comment]
Is there any new info about this?

**Comment by verelpode** [comment]
I can also confirm that when I use the "Run as administrator" command to run a test WPF app that uses WebView, the WebView doesn't work.  I don't see an error/exception, rather the WebView just remains blank.  
(Nuget package version 6.0.0-preview7.1 running in Windows 10 version 1903 build 18362.267)

I'm just making a wild guess here, but is it possible that this admin bug is related to issue #165 (WPF WebView crashes when "explorer.exe" is not running) ?   _Maybe_ `Windows.Web.UI.Interop.WebViewControlProcess` launches the "WWAHost.exe" process in a manner equivalent to `System.Diagnostics.ProcessStartInfo.UseShellExecute = true`.  

If that's what it does, then I think  `UseShellExecute = true` is unsupported when the app is elevated/admin (if I remember correctly).   Thus if `WebViewControlProcess` is modified to launch "WWAHost.exe" directly instead of launching via the shell/explorer, then _maybe_ 2 bugs will be solved at the same time:
1. Inability to run as admin/elevated.
2. Inability to run when "explorer.exe" is not running.

Or maybe they are totally separate issues.  I don't know.

**Comment by verelpode** [comment]
I investigated further and noticed that the WWAHost.exe instance isn't running at all, whenever the WPF app (with WebView) is running as admin.  I suggest that the solution _might_ be to make `Windows.Web.UI.Interop.WebViewControlProcess` execute the Win32 [GetCurrentProcessToken](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocesstoken) function followed by launching WWAHost.exe via either the [CreateProcessWithTokenW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) function or the [CreateProcessAsUserW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw) function, in order to grant the new WWAHost instance the same level of access (admin access) as the app using WebView.

HOWEVER, the above idea may be rejected because of the **security implications**.   Perhaps it's a bad idea to allow the web engine to process webpages while running as elevated admin.  So, to work around this, I can't really say because the full source code is unavailable, but I guess maybe consider using [Impersonation Tokens](https://docs.microsoft.com/en-us/windows/win32/secauthz/impersonation-tokens) after launching WWAHost using the elevated token, but do this while keeping in mind that impersonation doesn't really work in the manner that people expect it to.  Anyway, if possible, when creating the WebView's HWND, use the elevated/admin access, but when processing webpages, use a lower level of access.

In addition to invoking [GetCurrentProcessToken](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocesstoken), I also suggest invoking the [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop) function in order to help solve the bug described in #166.

**Comment by Que8549** [comment]
Any updates on this? This is still an issue in Microsoft.Toolkit.Forms.UI.Controls.WebView v6.0.

**Comment by Andreas-Hjortland** [comment]
I had the same problem, so I did some digging and figured out how to adapt the WebViewCompatible class, which falls back to Web browser controls on older versions of windows, to also check if the application is running as admin and falling back to using Web browser controls there as well. (see gist: https://gist.github.com/Andreas-Hjortland/94e55b1ce95cc78693b99e7f53c34366)

Can this be merged into the WebViewCompatible class if it's not possible to make WebView work when running the application as an administrator? I can create a pull request for it if you guys want that.

**Comment by michael-hawker** [comment]
@Andreas-Hjortland to clarify, your implementation just falls back to the old WPF WebBrowser control if running in Admin? Just as if instead the control was being used on Win 7 vs. Win 10?

@azchohfi foresee any problems with this approach if we wanted this as a short stop-gap in 6.1?  If not, I think it makes sense to take this small type of contribution, eh?

FYI @pagoe-msft

**Comment by Andreas-Hjortland** [comment]
@michael-hawker yeah, that is what is does

**Comment by michael-hawker** [comment]
@Andreas-Hjortland awesome, feel free to submit a PR. I believe we have unit tests around the WebView, so just make sure you add new ones for this scenario as well.  If you need to make breaking changes to the API surface to support this, let us know as we'd have to put it in a 7.0.0 branch for the future, our upcoming release is a minor 6.1 release. Thanks!

**Comment by Andreas-Hjortland** [comment]
@michael-hawker I have created a pull request in #250 . Fortunately this is not a breaking change and it does not change the API surface, so I created the pull request against the master branch.

**Comment by znakeeye** [comment]
Currently facing this problem in version `6.0.1`. Will you be able to use `WebViewCompatible` in an elevated process in the next version?

**Comment by michael-hawker** [comment]
@znakeeye I need to merge this for the 6.1 release, I haven't had a chance to do that yet. If you want to test out the PR in #250 and let me know if it works for your scenario, that'd be a big help!

**Comment by znakeeye** [comment]
It's a pity that `WebView` can't run as administrator. But, yes, a fallback to IE11 will do, for now. **When is 6.1 scheduled?** We need this before June.

Will try to verify the PR, but not sure how to do that effectively. I have limited experience with git and PR.

**Comment by znakeeye** [comment]
Any chance for an alpha/beta Nuget release of 6.1? Would be nice if we could start testing the upcoming release without going through the hassle of compiling everything on our side.

**Comment by michael-hawker** [comment]
@znakeeye 6.1 should ship on the 28th, that's the current plan. We have a [MyGet feed](https://dotnet.myget.org/gallery/uwpcommunitytoolkit) for anything that's in master, but looks like our last build had an error.

@azchohfi it's complaining about a cert in the sample app? We should just have those use the new setting and ignore a pfx, no?

**Comment by michael-hawker** [comment]
@znakeeye the myget feed has been updated from master. We'll have a preview on NuGet soon as well. Official ship date has moved back a week or so.
