### ISSUE TITLE
XAML Island doesn't respond to Windows app themes changes (Dark, Light) at run-time

### ISSUE THREAD

**Issue by Palatis** [windows-toolkit/Microsoft.Toolkit.Win32#228]
## Describe the bug
I have no idea if this issue should go here (or to `Microsoft.Toolkit.Win32`), but since the source code is here, I post it here.

I'm using `XamlIsland` in WPF to host my UWP custom control.
However it occasionally crash with `InvalidOperationException` says something like "Cannot create new view because main window is not created." (the actual message is "無法建立新的檢視，因為尚未建立主視窗", this is just a translation.)
with a stacktrace:
```
   at Windows.ApplicationModel.Core.CoreApplication.get_MainView()
   at Microsoft.Toolkit.Uwp.UI.Helpers.ThemeListener.Settings_ColorValuesChanged(UISettings sender, Object args) in D:\a\1\s\Microsoft.Toolkit.Uwp.UI\Helpers\ThemeListener.cs:line 81
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

I haven't switch the theme, tho... I just leave it there running for several minute and it crashes.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
1. follow the WPF XamlIsland [tutorial](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands) on Microsoft website
2. run the program and wait

## Expected behavior
no problem

## Screenshots
probably don't need one...

## Environment

NuGet Package(s):
```
<ItemGroup>
  <PackageReference Include="Microsoft.Toolkit.UI.XamlHost" Version="6.0.0" />
  <PackageReference Include="Microsoft.Toolkit.Wpf.UI.XamlHost" Version="6.0.0" />
</ItemGroup>
```

Package Version(s): 6.0.0

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (build number: 18363.535)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [x] 2019 Preview (version: 16.5.0)

## Additional context
currently no

**Comment by michael-hawker** [comment]
Thanks @Palatis for the report, moving it to the Win32 for initial triage as it's occurring with XAML Islands, though see now that the stack does have a toolkit component. Not sure where that reference is from.

@marb2000 @ocalvo @azchohfi thoughts?

**Comment by nc4rrillo** [comment]
I'm also running into this. I don't think we can call into CoreView in the context of a XAML Island.

For me, this was occurring because `RadialGauge` has a static `ThemeResource` field which sets up the event subscription to `ColorValuesChanged`. 

I think the effect of this is that any XAML Island application using the Windows Community Toolkit will crash on a color change.

I'll leave the fix up to you all, but I do have a workaround that I came up with to get my own app to stop crashing :-):

I run this in my app's main page `Loaded` event:

`

            var radialGaugeType = typeof(RadialGauge);
            var themeListener = radialGaugeType
                .GetField("ThemeListener", BindingFlags.NonPublic | BindingFlags.Static)
                .GetValue(null) as ThemeListener;
            themeListener.Dispose();
`

Calling `Dispose` unregisters the event subscription to `ColorValuesChanged`.

It won't help anyone who wishes to use `RadialGauge` or `MarkdownTextBlock` directly though.

**Comment by marb2000** [comment]
Doing the repro steps and I can't repro the bug...

**Comment by Palatis** [comment]
> Doing the repro steps and I can't repro the bug...

maybe try switch system theme in the control panel? this is really theme related.
it crashes on me everytime i switch theme.

sometimes my Windows 10 switch theme from dark to light and immediately back to dark randomly...
i dunno why... but it does......

**Comment by michael-hawker** [comment]
@azchohfi can you look at the [ThemeListener helper here](https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI/Helpers/ThemeListener.cs#L81) in the toolkit when you have time? Is there a different model we should be using that's more XAML Islands friendly due to it's use of `CoreWindow`?

**Comment by marb2000** [comment]
In UWP, the Application's RequestedTheme only changes in the constructor. So no sure what this helper is listening...

**Comment by Palatis** [comment]
@marb2000 so what actually happens if you switch theme from the control panel?
my other UWP apps actually switch theme (like from light to dark or vise versa).

**Comment by marb2000** [comment]
Gotcha! I get the scenario. now. You are listening the Window activation event to figure out whether the Theme has changed and then raised the event, am I right?

**Comment by marb2000** [comment]
@Palatis can you attach/link a repro project where we can see the "Cannot create new view because main window is not created." exception, please?

**Comment by Palatis** [comment]
Well you really just have to use the XamlIsland tutorial project and switch system theme...
Because that is what I did when I get the issue...

**Comment by marb2000** [comment]
OK. Let me change the title of the bug so it can be addressed properly
.
**Bug description**: XAML Islands doesn't respond Windows app themes changes (Dark, Light) dynamically, only at app start.

**Repro**: 
1. Run a XAML Islands app, for instance the WPF XamlIsland tutorial.
2. Switch the Color of the default app mode in Windows's settings

**Expected**:  The content of the XAML Island changes.
**Observed**: The context of the XAML Island doesn't change.

**Comment by nc4rrillo** [comment]
This is _crashing_ my XAML Islands application referencing the Windows Community Toolkit when changing the accent color on line 81 of ThemeListener.cs due to RunAsync:

`CoreApplication.MainView?.CoreWindow?.Dispatcher?.RunAsync`

Shouldn't this be using a `DispatcherQueue` instead in a XAML Island context? 
That's what I've been using elsewhere to run code on the UI Thread.

**Comment by marb2000** [comment]
@nc4rrillo Yes, using DispatcherQueue is the recommendation for UWP and XAML Islands given it works everywhere. If this doesn;t fix your bug, please, open a new bug within the repo steps, adding a project that fails is really helpful. Thanks!

**About the bug description:** Unfortunately, we can't fix this bug in the OS, but we can do it in WinUI 3 😊

**Comment by nc4rrillo** [comment]
@marb2000 thank you! The fix for this will have to come specifically from WCT in this instance, though I’d be happy to offer up a PR. 

cc: @michael-hawker

**Comment by michael-hawker** [comment]
@nc4rrillo Thanks! I don't know if we have another issue tracking this specifically in the [WCT](https://github.com/windows-toolkit/WindowsCommunityToolkit) repo, this issue may have started there, but I moved here originally due to the XAML Islands context, but there is indeed an issue in the toolkit.  If you don't mind filing an issue there for tracking with the specific details you've called out from ThemeListener, that'd be great for tracking!

I know my colleague @azchohfi has also been looking into these scenarios across the toolkit as well, so just coordinate with him in case he's already started something; otherwise, always happy for another hand and a PR!
