### ISSUE TITLE
Webview control not displaying any page

### ISSUE THREAD

**Issue by nareshmember** [windows-toolkit/Microsoft.Toolkit.Win32#32]
## Environment

```
Nuget Package(s): 

Package Version(s): 

Windows 10 Build Number:
- [ ] Creators Update (15063)
- [ ] Fall Creators Update (16299)
- [x ] April 2018 Update (17134)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Creators Update (15063)
- [ ] Fall Creators Update (16299)
- [x ] April 2018 Update (17134)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x ] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [x ] 2017 (version: )
- [ ] 2017 Preview (version: )

```
Webview control not loading any page... No event is invoking.
my system configuration is
Visual Studio 2017 .NetFramework 4.6.2 and 4.7.1
Windows 10 version 1803 OS Build 17134.81
My development machine is in **Hyper-V Manager**
Even I have tried github samples... same issue. no error showing in output window
what could be reason ?

Regards
Naresh

**Comment by omnjpa27516** [comment]
If user disables uac, webview will definitely break.
@rjmurillo Can you please tell me why not fix this bug?

**Comment by Ganeshcse** [comment]
Hi,
I am having same problem as @NikasZalias  mentioned. When I ran my VS as admin the application runs in admin mode and I am not able to see any web-page loading.

But when I opened VS (non-admin) and ran the application where I am using both WebView and WebViewCompatible controls, it works fine.

Can someone explain on how to achieve this if I want to run my application as admin but I wanted it to work for both WebView or WebCompatible controls without any issue.

**Comment by rjmurillo** [comment]
@niklaszalias @ganeshcse there is a limitation of the web view where it cannot run under admin mode--there is a system process that runs that would enable any code executing within the web view to also run as administrator and have some system level permissions.

CC @azchohfi

**Comment by Ganeshcse** [comment]
@rjmurillo Thanks for quick reply. I tried creating the application using VS 2015 with .Net 4.6.2 in non-admin mode and it works perfectly.

But I have two problems which I have identified when doing a basic R&D with the WebView control.

**Issue 1**
When I load the same web page using default WPF Web-Browser control, I can see some JavaScript error popups which are not shown when the same web page is loaded in Web View control.

Is this is a known issue or else I have missed something?

**Issue 2**
I could not able to do a right click on a web page that is loaded using WebView. But I am able to right click on a web page (same web page) when it is loaded using Web-Browser control.

Is this a known issue or does WebView does not allow right click by default?

or else is it some kind of permissions level that I am having and because of this it is not working.

Can you please let me know.

**Comment by rjmurillo** [comment]
@Ganeshcse The WebBrowser and WebView controls use different engines. Web Browser uses Trident (Internet Explorer) while Web View uses EdgeHTML (Edge). If you open your web page in each of those browsers, you should be able to see the differences as you mention. There is also some documentation about how to debug the web view control using the F12 tools in the documentation.

**Comment by james-wang-atx** [comment]
i download zip and ran and it hangs for me like other samples.
my OS:
Microsoft Windows [Version 10.0.18363.449]

**Comment by james-wang-atx** [comment]
sorry, i got it working, by not executing as administrator
