### ISSUE TITLE
Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated

### ISSUE THREAD

**Issue by mgomar** [windows-toolkit/Microsoft.Toolkit.Win32#76]
## I'm submitting a...
Bug report (I searched for similar issues and did not find one) 

## Current behavior
Get this error on runtime

> System.Exception: 'Catastrophic failure
>  
> WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later.  Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated.'

I am using an wpf and windows form project, so no manifest to set up this propperty. Or is there any other place I am missing?

## Expected behavior
I am using vs2019 preview and latest windows insider build, so there shopuld be no problem

## Minimal reproduction of the problem with instructions
Falis on runtime
`var toolbar = new InkToolbar();`

## Environment
Nuget Package(s): 
- Microsoft.Toolkit.Wpf.UI.Controls  (https://dotnet.myget.org/F/uwpcommunitytoolkit/api/v3/index.json")

Package Version(s): 
 - 6.0.0-preview1

Windows 10 Build Number:
- [x] Insider Build (10.0.18334.1 )

App min and target version:
?

Device form factor:
- [ x] Desktop

Visual Studio 
- [ x] 2019 Preview (version:16.0.0 preview 2.2 )

```

**Comment by DB1307** [comment]
I have the exact same Problem. 
Please suggest a solution.

**Comment by qmatteoq** [comment]
Hello, if you're running an app with XAML Islands on Windows 10 19H1, you need also to install the Preview SDK from the Insider website (https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) and set it as target SDK for the project.

**Comment by qmatteoq** [comment]
Otherwise, if you aren't using MSIX packaging, you need to add an app.manifest file to your WPF / Windows Forms project which states the minimum supported OS version, as shown here: https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.Toolkit.Sample.Wpf.App/app.manifest#L43

Then you need to declare the manifest in the .csproj file, as shown here: https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/blob/master/Microsoft.Toolkit.Sample.Wpf.App/Microsoft.Toolkit.Sample.Wpf.App.csproj#L6 

Thanks to @azchohfi for the hint 👍

**Comment by azchohfi** [comment]
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/pull/119 adds this to your manifest automatically. It's on MyGet right now, but the issue is fixed.
